steps:
- name: gcr.io/cloud-builders/docker
  id: Build
  args:
     - build
     - '--no-cache'
     - '-t'
     - 'gcr.io/$PROJECT_ID/python_script:$COMMIT_SHA'
     - .
     - '-f'
     - Dockerfile
- name: gcr.io/cloud-builders/docker
  id: Test
  args:
    - run
    - 'gcr.io/$PROJECT_ID/python_script:$COMMIT_SHA'
