steps:
- name: gcr.io/cloud-builders/docker
  id: Run
  args: ['run', '-d', '-p', '4444:4444', '--name', 'standalone-chrome', '--shm-size=2g', 'selenium/standalone-chrome:latest']
- name: gcr.io/cloud-builders/docker
  id: Build
  args:
     - build
     - '--no-cache'
     - '-t'
     - 'gcr.io/$PROJECT_ID/python_script:$COMMIT_SHA'
     - .
     - '-f'
     - Dockerfile
- name: gcr.io/cloud-builders/docker
  id: Test
  args:
    - run
    - 'gcr.io/$PROJECT_ID/python_script:$COMMIT_SHA'
