steps:
- name: gcr.io/cloud-builders/docker
  id: Run
  args: ['run', '-d', '-p', '4444:4444', '--name', 'standalone-chrome', 'selenium/standalone-chrome:4.2.1-20220531']
- name: python
  id: Test
  entrypoint: python
  args: ['selenium_python.py']
